CREATE DATABASE IF NOT EXISTS noteAppDb
CHARACTER SET utf8mb4
COLLATE utf8mb4_unicode_ci;
USE noteAppDb;


CREATE TABLE IF NOT EXISTS users (
userId INT UNSIGNED NOT NULL AUTO_INCREMENT,
userEmail VARCHAR(255) NOT NULL,
displayName VARCHAR(100) NOT NULL,
passwordHash VARCHAR(255) NOT NULL,
createdAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
updatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
ON UPDATE CURRENT_TIMESTAMP,
PRIMARY KEY (userId),
UNIQUE KEY uqUserEmail (userEmail)
) ENGINE=InnoDB
DEFAULT CHARSET=utf8mb4
COLLATE=utf8mb4_unicode_ci;


CREATE TABLE IF NOT EXISTS categories (
categoryId INT UNSIGNED NOT NULL AUTO_INCREMENT,
userId INT UNSIGNED NOT NULL,
categoryName VARCHAR(100) NOT NULL,
createdAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
PRIMARY KEY (categoryId),
UNIQUE KEY uqUserCategory (userId, categoryName),
CONSTRAINT fkCategoryUser
FOREIGN KEY (userId)
REFERENCES users (userId)
ON DELETE CASCADE
) ENGINE=InnoDB
DEFAULT CHARSET=utf8mb4
COLLATE=utf8mb4_unicode_ci;


CREATE TABLE IF NOT EXISTS notes (
noteId INT UNSIGNED NOT NULL AUTO_INCREMENT,
userId INT UNSIGNED NOT NULL,
categoryId INT UNSIGNED NULL DEFAULT NULL,
noteTitle VARCHAR(200) NOT NULL,
noteBody LONGTEXT NOT NULL,
isPinned TINYINT(1) NOT NULL DEFAULT 0,
createdAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
updatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
ON UPDATE CURRENT_TIMESTAMP,
PRIMARY KEY (noteId),
CONSTRAINT fkNoteUser
FOREIGN KEY (userId)
REFERENCES users (userId)
ON DELETE CASCADE,
CONSTRAINT fkNoteCategory
FOREIGN KEY (categoryId)
REFERENCES categories (categoryId)
ON DELETE SET NULL,
FULLTEXT INDEX ftNoteSearch (noteTitle, noteBody)
) ENGINE=InnoDB
DEFAULT CHARSET=utf8mb4
COLLATE=utf8mb4_unicode_ci;


CREATE TABLE IF NOT EXISTS tags (
tagId INT UNSIGNED NOT NULL AUTO_INCREMENT,
userId INT UNSIGNED NOT NULL,
tagName VARCHAR(50) NOT NULL,
createdAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
PRIMARY KEY (tagId),
UNIQUE KEY uqUserTag (userId, tagName),
CONSTRAINT fkTagUser
FOREIGN KEY (userId)
REFERENCES users (userId)
ON DELETE CASCADE
) ENGINE=InnoDB
DEFAULT CHARSET=utf8mb4
COLLATE=utf8mb4_unicode_ci;


CREATE TABLE IF NOT EXISTS note_tags (
noteId INT UNSIGNED NOT NULL,
tagId INT UNSIGNED NOT NULL,
PRIMARY KEY (noteId, tagId),
CONSTRAINT fkNoteTagNote
FOREIGN KEY (noteId)
REFERENCES notes (noteId)
ON DELETE CASCADE,
CONSTRAINT fkNoteTagTag
FOREIGN KEY (tagId)
REFERENCES tags (tagId)
ON DELETE CASCADE
) ENGINE=InnoDB
DEFAULT CHARSET=utf8mb4
COLLATE=utf8mb4_unicode_ci;